### ISSUE TITLE
World Not Loading

### ISSUE THREAD

**Issue by Diamondman121314** [jellysquid3/phosphor-fabric#1]
I use this mod in my usual client for doing anything, playing on multiplayer servers and all. I updated to 0.5.0+build.2 and it seems when attempting to join servers, specifically in my case Hypixel, it freezes on the "Joining world..." screen.

**Comment by jellysquid3** [comment]
Please upload a full log file from your client. It should contain additional information here as to what's going on.

**Comment by Diamondman121314** [comment]
https://gist.github.com/Diamondman121314/808200ab526e45025de98ee0476bb97f

**Comment by jellysquid3** [comment]
Thanks for the report. This issue was only triggering in some specific circumstances, and the code around it was rather fragile. In my testing, it can no longer be reproduced in Phosphor 0.5.1. If you continue to run into issues with the updated version, please re-open this issue.
