### ISSUE TITLE
Project URL leads to the wrong page

### ISSUE THREAD

**Issue by 1oglop1** [jellysquid3/phosphor-fabric#23]
Thank you for amazing mods, performance boost is enormous!

I noticed that all your mods point to your website directly `https://jellysquid.me` rather than the projects.
I assume this is some metadata either at courseforge or during the build

Example with phosphor

![image](https://user-images.githubusercontent.com/7480694/98093960-ed446480-1e88-11eb-8031-9be97abc3277.png)
 
When you click on the *Website* button 

![image](https://user-images.githubusercontent.com/7480694/98094014-fcc3ad80-1e88-11eb-8b34-77bde093b4ac.png)

Expected URL: `https://www.curseforge.com/minecraft/mc-mods/Phosphor`

Same goes with the multi-mc

![image](https://user-images.githubusercontent.com/7480694/98094075-1d8c0300-1e89-11eb-83fc-460d0b25f965.png)

The `Phosphor` URL leads to `https://jellysquid.me`

I'm not sure this is intentional but it would make updating of the mods much easier.

**Comment by DragonEggBedrockBreaking** [comment]
this seems intentional, as it is on multiple of her mods, including source code, but i agree that it seems out of place

**Comment by PhiProven** [comment]
736c4966e57976fd7b15663dbc6b7c1128c9161d changes the homepage to [CaffeineMc.net](http://CaffeineMc.net), which links to all our mods.
