### ISSUE TITLE
[Error loading] Invalid plugin.yml

### ISSUE THREAD

**Issue by Luffitys** [jellysquid3/phosphor-fabric#31]
I am using the PaperMC Server version paper-1.16.4-328.jar and have no plugins installed besides phosphor-fabric. I am using the latest phosphor-fabric release version phosphor-fabric-mc1.16.3-0.7.0+build.10.jar and experience an error in loading the plugin. The log can be found here: https://del.dog/cowulamuyt.txt

**Comment by Luffitys** [comment]
When compiling lithium-fabric with all the latest commits, the same error can be observed

**Comment by AMereBagatelle** [comment]
Phosphor is a fabric mod, not a plugin.  In order to run Phosphor, you must run a Fabric server instead of Paper.

**Comment by ReperakDev** [comment]
Lithium and Phosphor are Fabric mods, not Paper plugins. You can learn more about the Fabric modding toolchain at https://fabricmc.net

**Comment by Luffitys** [comment]
I see, only found out now that fabric servers exist. Thank you.
