### ISSUE TITLE
1.16.1 version

### ISSUE THREAD

**Issue by CodeNameEzra** [jellysquid3/phosphor-fabric#34]
Good evening, 
1.16.1 version has got "1.16.4" in version category.

**Comment by silversquirl** [comment]
The latest version of Phosphor is compatible with 1.16.1, 1.16.2, 1.16.3 and 1.16.4

**Comment by mrmangohands** [comment]
Actually the latest official release dropped 1.16.1 compatibility, you'll have to use 0.6.0 or a fork

**Comment by silversquirl** [comment]
Oops yeah. Regardless, 0.6.0 is compatible with 1.16.4, so it being tagged with that version is intended.
