### ISSUE TITLE
TNT machines deadlock the client

### ISSUE THREAD

**Issue by robot4jarvis** [jellysquid3/phosphor-fabric#36]
### Reproduction Step
1. Start a redstone machine that generates TNT continuously (with one to two TNT at a time it's enough).
2. Wait for some seconds or minutes.
3. The game crashes

### Crash Report File
No crash report was generated.
### Additional Information
It has happened many times.

**Comment by imt314** [comment]
i've done some testing and afaik the issue only appears in version 0.7.0

**Comment by PhiProven** [comment]
I think this is the same as #39 and should hence be fixed by  4c43554.
Feel free to reopen if the issue still occurs with Phosphor 0.7.1.
