### ISSUE TITLE
Phosphor reduces FPS by 3x

### ISSUE THREAD

**Issue by Pyxrs** [jellysquid3/phosphor-fabric#37]
Exactly what the title is. Fresh installation I get around 90 fps in normal survival, but with phosphor, I get around 30.

Specs:
CPU: AMD Ryzen 3 2200G
GPU: AMD Radeon RX 270

Seems like there is a severe bottleneck with AMD GPUs.

**Comment by Pyxrs** [comment]
It's been like this for earlier versions as well.

**Comment by TheRobified** [comment]
What version are you using? There is a build in Jelly's Discord that specifically addresses AMD cards. Not public, and still being tested. I'd join and ask for it, and see if you notice an improvement.

**Comment by dbl7id** [comment]
> What version are you using? There is a build in Jelly's Discord that specifically addresses AMD cards. Not public, and still being tested. I'd join and ask for it, and see if you notice an improvement.

I think you may be referring to sodium?

**Comment by Pyxrs** [comment]
I've been using Phosphor with this bug since 1.15 (I think) and I just identified what was causing the low fps now.

**Comment by jellysquid3** [comment]
Phosphor shouldn't be capable of bringing down average frame rates so much, and we've never had another report like this. Are you certain your game is using the right GPU device between Vanilla and Fabric?

**Comment by Pyxrs** [comment]
I've done four (non-professional) benchmarks:
Vanilla: ~60 fps
Fabric no mods: ~70 fps
Fabric w/ Sodium: ~130 fps
Fabric w/Sodium+Phosphor: ~50 fps

**Comment by Pyxrs** [comment]
In response to your question, no, I am not sure. How would I check?

**Comment by altrisi** [comment]
The easiest way to check that is finding the GPU in the top right corner of the F3 overlay, and make sure:
- It's the same in both tests
- It's the dedicated one in case you have multiple installed

It would also probably be good to know what is it in case the issue is hardware specific.

**Comment by Pyxrs** [comment]
Thanks for the tip, I will do that in the morning :)

**Comment by Pyxrs** [comment]
It looks like on all tests, it is using my GPU. I also noticed that once chunks were loaded, phosphor stopped performing so badly. However, as soon as I turned around, it goes down to 40 fps average again. This effect is multiplied on normal survival worlds, with lots of caves and trees and such.

**Comment by mrmangohands** [comment]
This is an odd issue, it would probably be easier to troubleshoot this over discord https://jellysquid.me/discord/

Otherwise if you could provide screenshots of each setup with f3 open at the exact same spot, daylight cycle off that would be the next step I suppose, after updating to 0.7.1

**Comment by Pyxrs** [comment]
It's not too big of a deal, I can live without Phosphor for now :) thanks for your willingness to help though!
