### ISSUE TITLE
Skylight Glitch in 1.16.5?

### ISSUE THREAD

**Issue by Hakatsc** [jellysquid3/phosphor-fabric#38]
In my survival world i made a classic mob farm and covered the top with bottom slabs the farm wasnt working in the day after searching for why i found that spawning areas had high sky light levels. Optimize world which fixed the issue temporarily but after a few minutes spawning layers had skylight access again i optimized again and loaded the map without phospor issue resolved so i imagine its caused by this mod. Ill post screenshots later when i am at home.

Other mods  Lithium,Sodium

**Comment by PhiProven** [comment]
Feel free to reopen if the issue still occurs with Phosphor 0.7.1 (after optimizing the world once).
