### ISSUE TITLE
Lighting glitches with C2ME-Fabric (formerly Barium-Fabric)

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [jellysquid3/phosphor-fabric#44]
Similar to a Tic-Tacs issue, but not the same. The following is copy-pasted from my respective issue on C2ME, with some modifications:

Chunks are completely dark, on all y levels, when paired with C2ME (cannot reproduce with Phosphor 0.7.0 and below). Happens in patches, which can be different sizes (e.g. some are 3-4 chunks, some are 7-8 chunks), and patches are not very common, (these are approximations, and you should 100% reproduce more scientifically and look into the code rather than going off my measurements). Bug is similar to [another issue](https://github.com/CaffeineMC/phosphor-fabric/issues/43), but is less severe, e.g. both skylight and blocklight are affected and occurs in chunks. You may need to fly around for a few minutes to reproduce, or sometimes you can reproduce quite quickly.

Hardware:
- i3 6100U (also reproduced with i7 7500U)
- 8GB 2133MHz RAM
- Intel HD Graphics 520 (also reproduced with Intel HD Graphics 620)

Software:
- LMDE (Linux Mint Debian Edition) 4 (also reproduced with Windows 10 2004)
- MultiMC 5; 0.6.11
- Minecraft 1.16.5
- Fabric 0.11.1
- OpenJDK 11
- C2ME 0.1.0-rc4
- Phosphor 0.7.1

Screenshot:
![2021-02-18_13 16 09](https://user-images.githubusercontent.com/68545280/108365290-f31f4500-71ee-11eb-83be-cdf76a0e034b.png)

![2021-02-20_10 43 35](https://user-images.githubusercontent.com/68545280/108593061-5cc35e80-7369-11eb-8b45-5015b7db6b8f.png)

**Comment by Genau6502** [comment]
That mod wildly throws threads at everything in the name of performance: I would really not advise using it

**Comment by DragonEggBedrockBreaking** [comment]
> That mod wildly throws threads at everything in the name of performance: I would really not advise using it

I am aware that is it incomplete/WIP, unstable and not recommended to be used. I was simply doing some testing for C2ME and noticed that Phosphor caused this issue. I just wanted to make sure that this bug can be seen by multiple sets of eyes from multiple angles, so that if/when C2ME becomes stable/usable/recommended, this bug doesn't persist.

**Comment by PhiProven** [comment]
Closing this as it is most likely a pure C2ME issue, see https://github.com/YatopiaMC/C2ME-fabric/issues/7#issuecomment-782747225.
