### ISSUE TITLE
White lines around blocks 

### ISSUE THREAD

**Issue by Akilli04** [jellysquid3/phosphor-fabric#53]
Blocks within a small distance suddenly have these odd white lines around them, how can I fix this?
![image](https://user-images.githubusercontent.com/84650864/119246361-a2224280-bb89-11eb-88e3-1886c2f23e03.png)
Also, dunno if it's related, but mobs and blocks that are within the white lines all become really bad looking all of a sudden.

**Comment by PhiProven** [comment]
This seems unlikely to be an issue with Phosphor.
You can join our [Discord](https://caffeinemc.net/discord) for troubleshooting.
