### ISSUE TITLE
1.17 version

### ISSUE THREAD

**Issue by thm51b8f2d68cs** [jellysquid3/phosphor-fabric#58]
I was curious if you have an estimated time frame for a 1.17 version of phosphor.

**Comment by Leo40Git** [comment]
An ETA is not available.

**Comment by spyvingen** [comment]
Will there be one atleast?

**Comment by Shroototem** [comment]
If you take a look at the "actions" page you'll see that they're trying to do that now.

**Comment by DragonEggBedrockBreaking** [comment]
> If you take a look at the "actions" page you'll see that they're trying to do that now.

No, that was in unofficial fork’s pull request which was not done properly, that’s not official work. You will only see progress in actions once a 1.17 branch is created.

**Comment by Shroototem** [comment]
@DragonEggBedrockBreaking 
I stand corrected. Thank you.

**Comment by cootshk** [comment]
So, will there be one? Lithium already has a 1.17 release, while sodium doesn't.

**Comment by thm51b8f2d68cs** [comment]
> 
> 
> So, will there be one? Lithium already has a 1.17 release, while sodium doesn't.

Please be patient.  They are modding this in their spare time and even simple mods take lots of time and effort; and they have lives and interests, hobbies.  It will be done soon.

**Comment by Felix14-v2** [comment]
> So, will there be one? Lithium already has a 1.17 release, while sodium doesn't.

You can use dev-versions of Sodium. Also besides Phosphor there is [Starlight](https://github.com/Tuinity/Starlight), which works great in 1.17.

**Comment by amnotbananaama** [comment]
Closing as a question, this should have been closed a long time ago
