### ISSUE TITLE
update for 1.17 / 1.17.1 ?

### ISSUE THREAD

**Issue by Maxtar07** [jellysquid3/phosphor-fabric#61]
Hi!
Just to know if there is an update planned for versions 1.17 / 1.17.1
Lithium is updated but not phosphor and sodium

Sincerely,
Maxtar07

**Comment by Leo40Git** [comment]
For one thing, Sodium is in fact updated for 1.17.1 - it's just not on CurseForge due to JellySquid having issues with her account on there.

Phosphor for 1.17 is being worked on, PhiPro is just busy with other things right now.

**Comment by Maxtar07** [comment]
Thank you for your answer. I will wait as long as it takes... ^^
