### ISSUE TITLE
[Bug] Phosphor crashing the game on game initialization.

### ISSUE THREAD

**Issue by krypciak-zz** [jellysquid3/phosphor-fabric#62]
Hi,
I'm running the latest version of Phosphor ( 0.7.2+build.12 ) with FabricAPI.
When trying to run the game, it crashes. Here's the log:
https://paste.ee/p/7UU2L
Using:
-Java 16.0.1 2021-04-20
-latest Fabric loader 0.11.6 6/24/21

Latest MultiMC (0.6.12 - 1530) launcher used.

The following mods: Sodium and Lithium work without any issues.

Thanks for your time.

**Comment by amnotbananaama** [comment]
Phosphor is currently not compatible with 1.17+
