### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by Grimfaast** [jellysquid3/phosphor-fabric#71]
I've tested it with other mods from the same creator and it's the only one that closes minecraft.

**Comment by CuboidRaptor** [comment]
r u using 1.17.x?
if so, Phosphor doesn't support 1.17.x yet.

**Comment by silversquirl** [comment]
If you're not using 1.17, a crash report would be helpful to diagnose this

**Comment by PhiProven** [comment]
Please open a new issue if this still happens with version 0.8.0.
