### ISSUE TITLE
Date of creator fabric mods for 1.18

### ISSUE THREAD

**Issue by MrPacha23** [jellysquid3/phosphor-fabric#72]
I want to know, when will the creator mods fabric come out for 1.18. Like phosphor, sodium, etc...

**Comment by EmqsaGit** [comment]
how is that an _*issue*_?

**Comment by MrPacha23** [comment]
How it's not?
I don't find a place to ask that, i want to know because i do streams and i want to start a world with the performance mods.

**Comment by jellysquid3** [comment]
When it's ready.
