### ISSUE TITLE
Lava light update issues [1.18.1]

### ISSUE THREAD

**Issue by TheSnowyChickens** [jellysquid3/phosphor-fabric#73]
Hello,

in the nether, some flowing lava create chunk based light issues. (second time this happend, relogging can fix it)
(it is a Vanilla - Paper Server with some datapacks)

![grafik](https://user-images.githubusercontent.com/29357962/146834262-333db1bf-c4c8-4930-ae1d-9ff538465f49.png)

Fabric-loader-0.12.11-1.18.1
Phosphor-fabric-mc1.18.x-0.8.1
![grafik](https://user-images.githubusercontent.com/29357962/146834335-72826c11-6542-4dcb-a524-0e9045580df8.png)

Reproduce:
find a lava spot, let the lava flow in many directions and remove the source.

With "Starlight" and no light engine mod, I can't create light issues.

**Comment by PhiProven** [comment]
I'm unable to redproduce the issue. This sounds like [MC-172980](https://bugs.mojang.com/browse/MC-172980), which would be a Vanilla bug.
Can you please test again with and without Phosphor on the exact same setup, i.e., same seed and coordinates.
In case it only happens with Phosphor, can you please also try with all other mods except Phosphor removed?

**Comment by TheSnowyChickens** [comment]
Oh
![grafik](https://user-images.githubusercontent.com/29357962/147130384-dc8ef667-1bfb-41a1-aade-78ea7b73e39c.png)
(/\ Vanilla only)

Then I am sorry. :D
I instantly played with fabric and never with pure vanilla on the server, so I could not experience this bug.

Is there maybe a chance that you can fix this vanilla bug with phosphor ?

(I close the issue)

**Comment by PhiProven** [comment]
Not really. A proper fix requires to validate the borders of all received lightmaps. Vanilla implemented this at some point, but it was removed again due to tremendous lag.
