### ISSUE TITLE
[Phosphor-0.8.1 | Fabric-0.7.7] Putting a solid block above a beacon at any point disables its light completely

### ISSUE THREAD

**Issue by antikovt** [jellysquid3/phosphor-fabric#77]
Ways to replicate: put a solid block 1 or more blocks higher than an activated beacon

Expected behaviour: beacon light cuts off at the placed block

Actual behaviour: there's no beacon light even below the placed block.

Could also be Sodium-Extra-0.4.0 or Lithium-0.7.7, but I think it must be Phosphor.

**Comment by Reefter7** [comment]
NOT AN ISSUE
This is a vanilla thing. This has nothing to do with any mod, but is the standard (intentional?) Minecraft behaviour. 
Following is in vanilla 1.18: https://streamable.com/qxgg6p
