### ISSUE TITLE
Audio delay

### ISSUE THREAD

**Issue by StephenLynx** [jellysquid3/phosphor-fabric#8]
When using phosphor, may audio seemed to be delayed. I'm using lithium, minihud and rougly enough items on 1.16.1. My OS is ubuntu 18.

**Comment by StephenLynx** [comment]
Following` squid's suggestion seems to have fixed it. Either I should've tested more throrougly (I tested like, 3 times) or it's pulseaudio being finnicky. You decide if you should close it or not.


```
JellySquid
by default you can run into strange issues like this... Minecraft in particular falls victim on my system

JellySquid
high-priority = yes
nice-level = -11

realtime-scheduling = yes
realtime-priority = 5

default-fragments = 2 
default-fragment-size-msec = 4 


JellySquid
you can modify your /etc/pulse/daemon.conf  to include these entries
```

**Comment by jellysquid3** [comment]
I'm going to close this as it's extremely unlikely Phosphor (or any of my other mods) have anything to do with this. More likely than not, just a poor default configuration for your system.
