### ISSUE TITLE
Phosphor + Create redstone links causes lighting to completely break

### ISSUE THREAD

**Issue by TropheusJ** [jellysquid3/phosphor-fabric#82]
[redstone links](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/content/logistics/block/redstone/RedstoneLinkBlock.java) from Create, when two are placed in the same chunk together, cause lighting to completely break in that chunk when Phosphor is installed.
Note that this image is from a lot of testing and a lot of chunk breaking.
![image](https://user-images.githubusercontent.com/60247969/170385687-6ae25f83-c79f-423e-a314-86fb122461ad.png)

Related: While trying to debug this, I put together [this code](https://gist.github.com/TropheusJ/65a4535ff1dad6d1840a939b2ba32ff5) to reset/resend chunk light. This works fine with Create alone or with Starlight.
This is the case with Phosphor as well, *on the first run*. On the second run, the client thread gets stuck permanently relighting the chunk, locking up the game.

**Comment by PhiProven** [comment]
See https://github.com/Fabricators-of-Create/Create/issues/318#issuecomment-1139572907.
