### ISSUE TITLE
Add 1.19.1 on Modrinth

### ISSUE THREAD

**Issue by rmnvgr** [jellysquid3/phosphor-fabric#85]
Hello, thank your for your work!

On Modrinth, version 1.19.1 is not listed as a supported version. Manually installing Phosphor works, but automated tools making use of the Modrinth API to install mods such as [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server/) can't install it with 1.19.1.

Is it possible to add 1.19.1 to supported versions, or does it need some testing beforehand?

**Comment by wolvyreen** [comment]
same applies to curseforge and 1.19.2.  Curseforge doesn't find the mod for 1.19.2 but manually installing works.

**Comment by sixwheeledbeast** [comment]
I have just run into this issue while using the Modrinth API.
Applies for 1.19.1 and 1.19.2 as above.

**Comment by PhiProven** [comment]
Done; sorry for the late response.

**Comment by rmnvgr** [comment]
Thank you!

**Comment by derekschinke** [comment]
Same issue with 1.19.3 now.

**Comment by PhiProven** [comment]
It's updated now.
