### ISSUE TITLE
Phosphor and Starlight mods are "incompatible" error

### ISSUE THREAD

**Issue by MTMomo99** [jellysquid3/phosphor-fabric#87]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Starlight' (starlight) 1.1.1+fabric.ae22326 with any version that is compatible with:
		 - phosphor, any version
	 - Replace mod 'Phosphor' (phosphor) 0.8.1 with any version that is compatible with:
		 - starlight, any version
Unmet dependency listing:
	 - Mod 'Phosphor' (phosphor) 0.8.1 is incompatible with any version of mod 'Starlight' (starlight), but a matching version is present: 1.1.1+fabric.ae22326!
	 - Mod 'Starlight' (starlight) 1.1.1+fabric.ae22326 is incompatible with any version of mod 'Phosphor' (phosphor), but a matching version is present: 0.8.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
	P.S.
	I added them both in my curseforge modpack and tried to load Minecraft but when I pressed "Launch" the fabric error code above showed and didn't give me any helpful information. Can I get some advice/help?

**Comment by mrjasonn** [comment]
Hi, both of them are completely different light engine improvements so you would have to choose one or use none. They are not compatible with each other.
