### ISSUE TITLE
Not working on my server

### ISSUE THREAD

**Issue by NgioKai21** [jellysquid3/phosphor-fabric#91]
Hello, I'm trying to use phosphor 1.19.2 0.8.1 but my server does not start with it dont know why, but when I just delete the mod it works. dont know why is not working.

**Comment by Timolino456** [comment]
If the server is crashing on start, you should post the crash log here, otherwise noone can help you.

**Comment by jellysquid3** [comment]
Closing as there hasn't been any follow up and there is literally no information for us to work from. Please don't open issues unless you are going to provide the bare minimum in debugging information.
