### ISSUE TITLE
Mention on the Phosphor Modrinth page that Phosphor is currently not needed on Minecraft 1.20+

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/phosphor-fabric#96]
Please mention on the Phosphor Modrinth page that Phosphor is currently not needed on Minecraft 1.20+ as in Minecraft 1.20 the light engine was heavily optimised and is much faster than Phosphor (according to [Starlight's LightBench tests](https://modrinth.com/mod/starlight) as of writing).

**Comment by DeadlyKitten37** [comment]
+1, please do this.

**Comment by jellysquid3** [comment]
Resolved with some recent cleanups to the page.
